<a href="https://colab.research.google.com/github/Prady96/SOC-Challenge/blob/master/SocialCopsChallenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## getting CSV from VPS to collab 'test csv'
!wget https://93.188.165.63/SocialCops/land_test.csv --no-check-certificate

--2018-11-14 09:46:55--  https://93.188.165.63/SocialCops/land_test.csv
Connecting to 93.188.165.63:443... connected.
WARNING: cannot verify 93.188.165.63's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
    WARNING: certificate common name ‘formpicture.com’ doesn't match requested host name ‘93.188.165.63’.
HTTP request sent, awaiting response... 200 OK
Length: 270242218 (258M) [text/csv]
Saving to: ‘land_test.csv’

land_test.csv       100%[===================>] 257.72M  4.03MB/s    in 2m 44s

2018-11-14 09:49:38 (1.58 MB/s) - ‘land_test.csv’ saved [270242218/270242218]

In [3]:
## Get data for 'train csv'
!wget https://93.188.165.63/SocialCops/land_train.csv --no-check-certificate

--2018-11-14 09:50:52--  https://93.188.165.63/SocialCops/land_train.csv
Connecting to 93.188.165.63:443... connected.
WARNING: cannot verify 93.188.165.63's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
    WARNING: certificate common name ‘formpicture.com’ doesn't match requested host name ‘93.188.165.63’.
HTTP request sent, awaiting response... 200 OK
Length: 15201595 (14M) [text/csv]
Saving to: ‘land_train.csv’

land_train.csv      100%[===================>]  14.50M  4.90MB/s    in 3.0s

2018-11-14 09:50:55 (4.90 MB/s) - ‘land_train.csv’ saved [15201595/15201595]

In [4]:
!ls

land_test.csv  land_train.csv  sample_data

In [0]:
import pandas as pd

In [0]:
## For Classification would be using Random Forest 
"""
1. I dont know much about data even not their column information so using Random Forest would be best I tried with genetic algorithem classification
but that somehow didnt work as i expected
2. dataset is large
"""

In [0]:
##Use case Implementation

#loading scikit random forest classifier library
from sklearn.ensemble import RandomForestClassifier

#loading pandas
import pandas as pd

#loading numoy
import numpy as np

#setting random seed
np.random.seed(0)

In [8]:
## dataFrame for the land_train csv
train = pd.read_csv("/content/land_train.csv")
## first 5 rows in the head column
train.head()

,X1,X2,X3,X4,X5,X6,I1,I2,I3,I4,I5,I6,target
0,323,229,120,517,209,115,0.623234,-1.047476,1.473405,0.380537,-0.021277,0.424242,1
1,335,220,109,387,149,89,0.560484,-1.004514,1.200777,0.324813,-0.101010,0.444030,1
2,255,150,52,184,72,45,0.559322,-0.996822,0.825000,0.300728,-0.072165,0.437500,1
3,254,182,73,413,156,84,0.699588,-1.151258,1.425354,0.436268,0.070064,0.451670,1
4,257,219,100,722,254,130,0.756691,-1.236199,1.990973,0.506155,0.130435,0.479508,1

In [9]:
## testing data
test = pd.read_csv("/content/land_test.csv")
test.head()

,X1,X2,X3,X4,X5,X6,I1,I2,I3,I4,I5,I6
0,338,554,698,1605,1752,1310,0.393834,-0.350045,1.565423,0.311659,0.304781,-0.043789
1,667,976,1187,1834,1958,1653,0.214167,-0.181467,1.050679,0.196439,0.164085,-0.032700
2,249,420,402,1635,1318,736,0.605302,-0.712650,2.268984,0.441984,0.293497,0.107348
3,111,348,279,1842,743,328,0.736917,-1.162062,3.074176,0.551699,0.080725,0.425145
4,349,559,642,1534,1544,989,0.409926,-0.406678,1.607795,0.323984,0.212753,-0.003249

In [10]:
print("number of observations in train data: ",len(train))
print("number of observations in test data: ",len(test))

number of observations in train data:  110000
number of observations in test data:  2000000

In [12]:
## list of the features columns for the data
features = train.columns[:12]
print(features)

Index(['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6'], dtype='object')

In [13]:
# Factorise each target
y = pd.factorize(train['target'])[0]
print(y)

[0 0 0 ... 3 3 3]

In [18]:
## Checking if theirs difference bw test and train
train.columns.equals(test.columns)

False

In [19]:
## As the ans is 'false' lets check the difference bw them
train.columns.difference(test.columns)

Index(['target'], dtype='object')

In [0]:
## Difference bw them is target
## create a columns in test dataset
test['target'] = ""

In [21]:
#check the test set
test

,X1,X2,X3,X4,X5,X6,I1,I2,I3,I4,I5,I6,target
0,338,554,698,1605,1752,1310,0.393834,-0.350045,1.565423,0.311659,0.304781,-0.043789,
1,667,976,1187,1834,1958,1653,0.214167,-0.181467,1.050679,0.196439,0.164085,-0.032700,
2,249,420,402,1635,1318,736,0.605302,-0.712650,2.268984,0.441984,0.293497,0.107348,
3,111,348,279,1842,743,328,0.736917,-1.162062,3.074176,0.551699,0.080725,0.425145,
4,349,559,642,1534,1544,989,0.409926,-0.406678,1.607795,0.323984,0.212753,-0.003249,
5,363,496,501,833,800,564,0.248876,-0.269084,0.821571,0.215513,0.059155,0.020208,
6,538,821,837,1224,1159,1034,0.187773,-0.215049,0.792773,0.189002,0.105291,0.027277,
7,560,683,680,1018,965,764,0.199058,-0.225785,0.759024,0.168196,0.058172,0.026727,
8,607,758,818,1164,1374,1142,0.174571,-0.091829,0.686800,0.153604,0.165306,-0.082742,
9,231,434,363,2102,1167,568,0.705477,-0.991497,3.041530,0.509306,0.220193,0.286020,
10,343,553,568,1848,1658,971,0.529801,-0.583994,2.161743,0.395141,0.261858,0.054193,
11,317,515,542,1993,1668,952,0.572387,-0.661160,2.398101,0.415042,0.274431,0.088774,
12,428,610,715,1675,2039,1402,0.401674,-0.303666,1.575253,0.307034,0.324516,-0.098008,
13,245,476,364,2633,1510,689,0.757090,-1.028150,3.525145,0.544320,0.308642,0.271060,
14,435,624,774,1308,1652,1354,0.256484,-0.140268,0.981512,0.220064,0.272556,-0.116216,
15,241,477,481,1481,1009,609,0.509684,-0.699242,2.004012,0.403231,0.117431,0.189558,
16,614,856,1109,1913,2511,1817,0.266049,-0.130877,1.208783,0.221229,0.241969,-0.135172,
17,487,694,824,1462,1800,1509,0.279090,-0.175473,1.117066,0.234773,0.293613,-0.103617,
18,494,743,1018,2184,2553,1668,0.364147,-0.286250,1.694130,0.282881,0.241996,-0.077897,
19,357,613,664,1848,1600,1031,0.471338,-0.543263,2.016360,0.366645,0.216519,0.071926,
20,566,823,1118,2129,3015,2073,0.311364,-0.139125,1.409616,0.250482,0.299279,-0.172240,
21,469,670,718,1633,1505,1051,0.389196,-0.429986,1.633408,0.304650,0.188242,0.040790,
22,277,496,427,2247,1396,704,0.680628,-0.914227,3.015378,0.491905,0.244916,0.233599,
23,342,531,548,1674,1644,1007,0.506751,-0.515792,1.954790,0.379637,0.295177,0.009042,
24,434,637,681,2139,1792,1098,0.517021,-0.605294,2.325445,0.377615,0.234401,0.088273,
25,224,409,337,1737,1107,557,0.675024,-0.896543,2.625205,0.494894,0.246085,0.221519,
26,557,705,768,975,876,642,0.118761,-0.172245,0.481135,0.116682,-0.089362,0.053485,
27,505,738,954,1858,2583,1802,0.321479,-0.158228,1.356526,0.259139,0.307692,-0.163252,
28,462,680,841,2092,2114,1329,0.426526,-0.421295,1.928958,0.320647,0.224885,-0.005231,
29,327,558,632,1625,1358,937,0.439965,-0.529472,1.818120,0.346656,0.194391,0.089507,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999970,419,679,750,2004,1911,1189,0.455338,-0.479092,2.004157,0.351849,0.226405,0.023755,
1999971,664,826,899,1390,1580,1254,0.214504,-0.150531,0.900955,0.179740,0.164886,-0.063973,
1999972,554,837,900,1543,1417,1175,0.263201,-0.305769,1.181858,0.235089,0.132530,0.042568,
1999973,174,374,285,2217,1130,531,0.772182,-1.096951,3.339483,0.556301,0.301471,0.324768,
1999974,411,602,646,1717,1598,1031,0.453237,-0.489135,1.860149,0.343100,0.229577,0.035897,
1999975,601,833,1157,2257,3342,2235,0.322203,-0.128418,1.470068,0.250962,0.317807,-0.193785,
1999976,703,922,1047,2023,2266,1718,0.317915,-0.261259,1.490293,0.250664,0.242676,-0.056657,
1999977,260,419,418,1505,1293,748,0.565263,-0.641031,2.054971,0.415263,0.283019,0.075768,
1999978,733,1093,1486,2639,2898,2125,0.279515,-0.232739,1.549502,0.234406,0.176959,-0.046776,
1999979,355,590,643,1938,1815,1075,0.501744,-0.534517,2.113881,0.378977,0.251455,0.032774,
1999980,290,560,624,1833,1891,1253,0.492063,-0.476489,1.981169,0.384303,0.335109,-0.015575,
1999981,229,446,399,2437,1479,730,0.718618,-0.963255,3.256738,0.509742,0.293180,0.244637,
1999982,430,589,668,1768,1986,1253,0.451560,-0.393489,1.795335,0.332552,0.304529,-0.058071,
1999983,333,583,592,2101,1630,957,0.560342,-0.686581,2.470453,0.417859,0.235636,0.126240,
1999984,341,628,719,2140,1928,1175,0.497027,-0.549141,2.227941,0.380862,0.240760,0.052114,
1999985,383,551,565,1741,1650,962,0.509974,-0.536810,2.019498,0.374849,0.259987,0.026836,
1999986,483,680,699,1743,1217,810,0.427518,-0.605221,1.918910,0.327067,0.073559,0.177703,
1999987,345,584,544,2192,1619,892,0.602339,-0.752693,2.669548,0.443161,0.242340,0.150354,
1999988,373,611,686,1755,1740,1176,0.437935,-0.442227,1.808232,0.342528,0.263158,0.004292,
1999989,338,610,672,2345,2064,1196,0.554524,-0.618258,2.519567,0.410202,0.280514,0.063733,
1999990,368,609,633,901,847,708,0.174707,-0.205599,0.641009,0.189962,0.055928,0.030892,
1999991,195,360,342,1645,1031,557,0.655762,-0.885209,2.518845,0.472496,0.239155,0.229447,
1999992,615,857,1205,2085,3127,2303,0.267477,-0.067554,1.218935,0.218940,0.312999,-0.199923,
1999993,210,420,356,2135,1424,677,0.714171,-0.913946,2.982030,0.515299,0.310745,0.199775,
1999994,468,668,786,1379,1654,1388,0.273903,-0.183234,1.076759,0.232095,0.276909,-0.090669,
1999995,232,500,481,1715,1088,613,0.561931,-0.785620,2.330792,0.438636,0.120658,0.223689,
1999996,231,407,413,1363,1041,595,0.534910,-0.668853,1.937565,0.405925,0.180556,0.133943,
1999997,407,529,607,857,908,828,0.170765,-0.141870,0.595069,0.155119,0.154007,-0.028895,
1999998,376,589,607,1543,1339,903,0.435349,-0.506133,1.743528,0.342194,0.196026,0.070784,
1999999,567,858,989,2121,2249,1689,0.363987,-0.334697,1.712402,0.292641,0.261389,-0.029291,

In [14]:
## Actual start of the prediction here
# creating a random forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Training the classifier
## Fitting the data and here y is target
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [22]:
#Applying the trained Classifier to the test
clf.predict(test[features])

array([2, 3, 0, ..., 2, 0, 3])

In [24]:
# check predicting data for the first 10
clf.predict_proba(test[features])[0:10]

array([[0.3, 0. , 0.4, 0.3],
       [0. , 0. , 0.2, 0.8],
       [1. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. ],
       [0.4, 0. , 0.1, 0.5],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0.9, 0.1],
       [0. , 0. , 1. , 0. ],
       [0. , 0. , 0.9, 0.1],
       [1. , 0. , 0. , 0. ]])

In [25]:
## checking names for target for predicated class
test['target'].head()

0
1
2
3
4
Name: target, dtype: object

In [29]:
preds = pd.unique(train[['target']].values.ravel('K'))[clf.predict(test[features])]
preds[0:20]

array([4, 3, 1, 1, 3, 4, 4, 4, 4, 1, 1, 1, 4, 1, 4, 1, 3, 3, 4, 3])

In [30]:
pd.crosstab(test['target'],preds,rownames=['Actual Target'],
           colnames = ['Predicted target'])

Predicted target       1     2       3       4
Actual Target
                  997609  2115  331405  668871

In [0]:
## Refernces taken for errors
## Empty Column error : https://stackoverflow.com/questions/16327055/how-to-add-an-empty-column-to-a-dataframe
## String error :       https://stackoverflow.com/questions/8420143/valueerror-could-not-convert-string-to-float-id
## Multiple coluumns :  https://stackoverflow.com/questions/26977076/pandas-unique-values-multiple-columns

## pandas errors      : https://www.youtube.com/watch?v=7gAZoK6kGhM&t=2294s